import assert from "node:assert/strict";
import test from "node:test";
import {verifyConfirmation,type VerificationAuth} from "../src/lib/email-verification";
function fixture(){const calls:unknown[]=[];const success={data:{user:{email_confirmed_at:"2026-10-08"}},error:null};const auth:VerificationAuth={verifyOtp:async options=>{calls.push(options);return success;},exchangeCodeForSession:async code=>{calls.push(code);return success;},signOut:async options=>{calls.push(options);return {error:null};}};return {auth,calls};}
test("Missing, ambiguous, and unrelated links never create an auth session",async()=>{for(const value of ["","code=a&token_hash=b&type=email","token_hash=a&type=recovery"]){assert.equal(await verifyConfirmation(new URLSearchParams(value),async()=>{throw Error("must not run");}),"invalid");}});
test("Email token hashes confirm across browsers and end only the confirmation session",async()=>{const {auth,calls}=fixture();assert.equal(await verifyConfirmation(new URLSearchParams("token_hash=hash&type=email"),async()=>auth),"verified");assert.deepEqual(calls,[{token_hash:"hash",type:"email"},{scope:"local"}]);});
test("Existing PKCE confirmation links also prompt a fresh sign-in",async()=>{const {auth,calls}=fixture();assert.equal(await verifyConfirmation(new URLSearchParams("code=pkce"),async()=>auth),"verified");assert.deepEqual(calls,["pkce",{scope:"local"}]);});
test("Expired links cannot display verified success or sign out an existing session",async()=>{const {auth,calls}=fixture();auth.verifyOtp=async()=>({data:{user:null},error:Error("expired")});assert.equal(await verifyConfirmation(new URLSearchParams("token_hash=expired&type=email"),async()=>auth),"invalid");assert.deepEqual(calls,[]);});
test("An unconfirmed address never receives a success result",async()=>{const {auth}=fixture();auth.verifyOtp=async()=>({data:{user:{email_confirmed_at:null}},error:null});assert.equal(await verifyConfirmation(new URLSearchParams("token_hash=hash&type=email"),async()=>auth),"invalid");});
test("A failed sign-out cannot report a completed confirmation flow",async()=>{const {auth}=fixture();auth.signOut=async()=>({error:Error("offline")});assert.equal(await verifyConfirmation(new URLSearchParams("code=pkce"),async()=>auth),"signout_failed");});
