"use client";
import AuthForm from "./auth-form";
import { browserAuth } from "@/lib/auth-client";
import { useState, type FormEvent } from "react";
import { Icon } from "./components/brand";
import { money, licenseNames, type Receipt, type ReceiptItem } from "@/lib/catalog";
export type AccountData = { identity: {id:string;email:string}; profile: {id:string;name:string;email:string} | null; orders: Receipt[]; isAdmin:boolean };
export default function AccountPanel({ data, loading, onUpdated, onReceipt, onAudioPlay }: { data:AccountData|null; loading:boolean; onUpdated:()=>Promise<void>; onReceipt:(token:string)=>void; onAudioPlay:()=>void }) {
  const [name,setName]=useState(data?.profile?.name ?? ""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[accepted,setAccepted]=useState(false);
  const [editing,setEditing]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true);setError("");
    try {const response=await fetch("/api/account",{method:"POST",headers:{"Content-Type":"application/json"},signal:AbortSignal.timeout(15000),body:JSON.stringify({name,acceptedTerms:data?.profile ? true:accepted})});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error || "Could not save your account.");await onUpdated();setEditing(false);}
    catch(error){setError(error instanceof Error ? error.message:"Could not save your account.");}finally{setBusy(false);}
  }
  if(loading)return <p className="receipt-loading" role="status">Loading your account…</p>;
  if(!data)return <AuthForm onUpdated={onUpdated}/>;
  if(!data.profile || editing)return <form className="account-create" onSubmit={submit}><p className="panel-subtitle">{data.profile ? "Update your display name.":"You're signed in. Finish creating your Melvey account below."}</p><div className="form-field"><label htmlFor="account-name">Display name</label><input id="account-name" value={name} minLength={2} maxLength={60} required disabled={busy} onChange={event=>setName(event.target.value)} autoComplete="nickname" placeholder="Your artist name"/></div><div className="account-email"><span>Signed-in email</span><strong>{data.identity.email}</strong></div>{!data.profile ? <label className="terms"><input type="checkbox" required checked={accepted} onChange={event=>setAccepted(event.target.checked)}/><span>Create a Melvey account and save my profile and purchases on this platform.</span></label>:null}{error?<p className="checkout-error" role="alert">{error}</p>:null}<button className="primary-button wide" disabled={busy}>{busy?"Saving…":data.profile?"Save changes":"Create my account"}<Icon name="arrow" size={18}/></button>{editing?<button type="button" className="text-button wide" onClick={()=>setEditing(false)}>Cancel</button>:null}<p className="charge-note">Your profile is saved to your Melvey account.</p></form>;
  const library=new Map<string,{item:ReceiptItem;order:Receipt}>();
  for(const order of data.orders)for(const item of order.items)if(!library.has(item.beatId))library.set(item.beatId,{item,order});
  return <div className="account-library"><div className="account-profile"><div><strong>{data.profile.name}</strong><span>{data.identity.email}</span></div><button className="text-button" onClick={()=>{setName(data.profile!.name);setEditing(true);}}>Edit profile</button></div><div className="library-heading"><h3>My beats</h3><span>{library.size} {library.size===1?"beat":"beats"}</span></div>{library.size?<div className="library-list">{[...library.values()].map(({item,order})=><article className="library-item" key={item.beatId}><img src={item.artworkUrl || `/art/${item.beatId}.svg`} alt="" width={64} height={64}/><div><h4>{item.title}</h4><span>{licenseNames[item.license]} · {item.bpm ?? "—"} BPM</span><audio controls preload="none" src={item.previewUrl || `/audio/${item.beatId}.wav`} aria-label={`Play purchased ${item.title}`} onPlay={event=>{onAudioPlay();const current=event.currentTarget;current.closest(".library-list")?.querySelectorAll("audio").forEach(audio=>{if(audio!==current)audio.pause();});}}/><div className="library-actions"><a href={item.downloadUrl || `/audio/${item.beatId}.wav`} download><Icon name="download" size={14}/> Download audio</a><button onClick={()=>onReceipt(order.token)}>Receipt</button></div></div></article>)}</div>:<div className="library-empty"><Icon name="cart" size={30}/><h4>Your library is ready.</h4><p>Beats from completed purchases will appear here automatically.</p></div>}<div className="library-heading orders-heading"><h3>Orders</h3><span>{data.orders.length}</span></div>{data.orders.map(order=><button className="order-list-item" key={order.token} onClick={()=>onReceipt(order.token)}><span><strong>{order.id}</strong><small>{new Date(order.createdAt).toLocaleDateString("en-US")} · {order.items.length} {order.items.length===1?"beat":"beats"}</small></span><b>{money(order.total)}</b><Icon name="arrow" size={16}/></button>)}<div className="account-footer">{data.isAdmin?<a href="/studio">Open administrator studio</a>:<span>Melvey account library</span>}<button className="text-button" onClick={async()=>{await browserAuth().auth.signOut();await onUpdated();}}>Sign out</button></div></div>;
}
