"use client";
import { useState,type FormEvent } from "react";
import { browserAuth } from "@/lib/auth-client";
import { Icon } from "./components/brand";
export default function AuthForm({onUpdated}:{onUpdated:()=>Promise<void>}){
  const [signup,setSignup]=useState(false),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState(""),[accepted,setAccepted]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");setMessage("");try{
    const client=browserAuth();
    if(signup){const {data,error}=await client.auth.signUp({email,password,options:{data:{name},emailRedirectTo:`${window.location.origin}/auth/callback`}});if(error)throw error;if(!data.session){setMessage("Check your email to confirm your account, then return here to log in.");return;}const response=await fetch("/api/account",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,acceptedTerms:accepted})});if(!response.ok)throw new Error("Signed up successfully. Finish your account after logging in.");}
    else{const {error}=await client.auth.signInWithPassword({email,password});if(error)throw error;}
    setPassword("");await onUpdated();
  }catch(e){setError(e instanceof Error?e.message:"Could not sign in.");}finally{setBusy(false);}}
  return <form className="account-create" onSubmit={submit}><div className="auth-tabs"><button type="button" className={!signup?"selected":""} onClick={()=>{setSignup(false);setError("");setMessage("");}}>Log in</button><button type="button" className={signup?"selected":""} onClick={()=>{setSignup(true);setError("");setMessage("");}}>Create account</button></div><p className="panel-subtitle">Your beats, receipts, and downloads. Together.</p>{signup?<div className="form-field"><label htmlFor="signup-name">Display name</label><input id="signup-name" autoComplete="nickname" minLength={2} maxLength={60} required value={name} onChange={e=>setName(e.target.value)}/></div>:null}<div className="form-field"><label htmlFor="auth-email">Email</label><input id="auth-email" type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} disabled={busy}/></div><div className="form-field"><label htmlFor="auth-password">Password</label><input id="auth-password" type="password" autoComplete={signup?"new-password":"current-password"} minLength={signup?8:1} maxLength={256} required value={password} onChange={e=>setPassword(e.target.value)} disabled={busy}/>{signup?<small>Use at least 8 characters.</small>:null}</div>{signup?<label className="terms"><input type="checkbox" required checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>Create a Melvey account and save my profile and purchases.</span></label>:null}{error?<p className="checkout-error" role="alert">{error}</p>:null}{message?<p className="studio-notice" role="status">{message}</p>:null}<button className="primary-button wide" disabled={busy}>{busy?"Please wait…":signup?"Create my account":"Log in"}<Icon name="arrow" size={18}/></button><p className="charge-note">Keep your purchased beats and downloads in one place.</p></form>;
}
